# NUMPY

In [2]:
#import the enumpy library

import numpy as np

NUMPY ARRAY

In [11]:
#1D array

arr=np.array([1,2,3,4])
print(arr)

print(type(arr))

#to know the dimesnion of array 
print(arr.shape)

print(arr[0],arr[1],arr[2])

#replace value 
arr[1]=5
print(arr)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
1 2 3


array([1, 5, 3, 4])

In [24]:
#2D ARRAY

arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

#to know the dimension
print(arr1.ndim)

print(arr1.size)

#location of array
print(arr1.data)

[[1 2 3 4]
 [5 6 7 8]]
2
8


In [23]:
#numpy provides many functions to create array
a=np.zeros((2,2))
print(a)

a=np.ones((2,2))
print(a)

c=np.full((2,2),5)
print(c)


[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[5 5]
 [5 5]]


In [28]:
#identity matrix
d=np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
#create array with random values
e=np.random.random((2,2))
e

array([[0.55039045, 0.71237751],
       [0.43248877, 0.73429045]])

# ARRAY INDEXING

In [53]:
from numpy import random as r
x=r.randint(1000)
print(x)

y=r.rand(2)
print(y)

p=r.randint(1000,size=(2,2))
r.seed(101) #put some value here so that it remains same everytime
print(p)

519
[0.49201605 0.73150955]
[[294 750]
 [329 436]]


In [54]:
#3D ARRAY

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# ARRAY MATH

In [62]:
x = np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

print(np.sqrt(x))


[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [64]:
print(np.sum(x))
x

10


array([[1, 2],
       [3, 4]])

In [66]:
print(np.sum(x,axis=0)) #colums addition

print(np.sum(x,axis=1)) #rows addition



[4 6]
[3 7]


In [69]:
#transpose

print(x.T)

print(y.T)


[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [80]:
#calculate the BMI of cricket player

#heights of players in inches
height_in = [61,56,62,65,64,63,62,62,73,75,80]

#convert in to numpyarray

ht_np=np.array(height_in)
ht_np = ht_np * 0.0245 #converting into meters
print(ht_np)


#weights of players
weight_pd = [100,104,120,130,140,145,106,108,110,119,135]

#convert into numpyarray
wt_np=np.array(weight_pd)

wt_np=wt_np * 0.45          #converting into kgs    
print(wt_np)



#calculating BMI

bmi=wt_np/ht_np**2
bmi

[1.4945 1.372  1.519  1.5925 1.568  1.5435 1.519  1.519  1.7885 1.8375
 1.96  ]
[45.   46.8  54.   58.5  63.   65.25 47.7  48.6  49.5  53.55 60.75]


array([20.1474773 , 24.86208978, 23.40335994, 23.0673117 , 25.62408892,
       27.38843698, 20.67296795, 21.06302395, 15.47488071, 15.86005831,
       15.81372345])

In [81]:
bmi[-1]

15.8137234485631

In [82]:
bmi[bmi<21]

array([20.1474773 , 20.67296795, 15.47488071, 15.86005831, 15.81372345])

In [88]:
#make one array with heights and weights

players=np.array([wt_np,ht_np])
print(players)
print(players.shape)

pT=players.T
pT.shape

[[45.     46.8    54.     58.5    63.     65.25   47.7    48.6    49.5
  53.55   60.75  ]
 [ 1.4945  1.372   1.519   1.5925  1.568   1.5435  1.519   1.519   1.7885
   1.8375  1.96  ]]
(2, 11)


(11, 2)

In [89]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

STATISTICAL FUNCION

In [92]:
print(np.mean(ht_np))
print(np.median(ht_np))
print(np.sum(ht_np))
print(np.std(ht_np))
print(np.corrcoef(ht_np,wt_np)) #2 arguments required
print(np.amax(ht_np))
print(np.amin(ht_np))


1.6103181818181818
1.5435
17.7135
0.16717903749726634
[[1.         0.32982522]
 [0.32982522 1.        ]]
1.96
1.372


In [104]:
#boolean

bools=[False,True,True,True,False]
b=np.array(bools)
print(b)

b.sum() #true=1 false=0

b.any() #gives if there is any value true in the array

names=np.array(['bob','joe','bob','scott','bob'])
print(names)
np.unique(names)




[False  True  True  True False]
['bob' 'joe' 'bob' 'scott' 'bob']


array(['bob', 'joe', 'scott'], dtype='<U5')